### ISSUE TITLE
关于实验结果 

### ISSUE THREAD

**Issue by srtianxia** [LunaBlack/KGAT-pytorch#1]
您好，感谢您这么棒的工作，我想问下不使用pre_train的embedding加载的话，您有试过吗，我尝试跑yelp数据，不加载embedding的话，前10几轮的指标特别低，而且没有上涨的趋势，谢谢！

**Comment by LunaBlack** [comment]
我并没有尝试过。关于实验效果的问题，建议咨询论文原作者
