### ISSUE TITLE
About the kg_loss

### ISSUE THREAD

**Issue by PenguinCats** [LunaBlack/KGAT-pytorch#7]
https://github.com/LunaBlack/KGAT-pytorch/blob/e7305c3e80fb15fa02b3ec3993ad3a169b34ce64/model/KGAT.py#L156
I'm sorry to raise such a silly question.
I wonder why 'torch. mean ()' is used here.
According to the Equation (2), why it isn't 'sum'.

**Comment by liulu1998** [comment]
@Hencent 

https://github.com/LunaBlack/KGAT-pytorch/blob/e7305c3e80fb15fa02b3ec3993ad3a169b34ce64/model/KGAT.py#L156
The above line calculates the **average** loss of a **batch**, 
while the following two lines **add up** the **plausibility score** of positive and negative samples, respectively.

https://github.com/LunaBlack/KGAT-pytorch/blob/e7305c3e80fb15fa02b3ec3993ad3a169b34ce64/model/KGAT.py#L151-L152

**Comment by PenguinCats** [comment]
Thank you for your patience. I used to think that I should sum the loss of positive and negative sample pairs in a batch.
